// <auto-generated />
using System;
using CubeTimer.WebApi.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CubeTimer.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250109222110_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentTokenId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentTokenId")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Auth.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Cubes.Entities.Cube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CubeEvent")
                        .HasColumnType("integer");

                    b.Property<string>("CubeMake")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CubeEvent");

                    b.HasIndex("CubeMake");

                    b.HasIndex("UserId");

                    b.ToTable("Cubes", (string)null);
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Sessions.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("SessionName")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Description");

                    b.HasIndex("SessionName");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Solves.Entities.Solve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CubeId")
                        .HasColumnType("integer");

                    b.Property<string>("Scramble")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("SolveModifier")
                        .HasColumnType("integer");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CubeId");

                    b.HasIndex("Scramble");

                    b.HasIndex("SessionId");

                    b.HasIndex("SolveModifier");

                    b.HasIndex("Time");

                    b.HasIndex("UserId");

                    b.ToTable("Solves", (string)null);
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("CubeTimer.WebApi.Contexts.Auth.Entities.RefreshToken", "ParentToken")
                        .WithOne("ChildToken")
                        .HasForeignKey("CubeTimer.WebApi.Contexts.Auth.Entities.RefreshToken", "ParentTokenId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CubeTimer.WebApi.Contexts.Auth.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Cubes.Entities.Cube", b =>
                {
                    b.HasOne("CubeTimer.WebApi.Contexts.Auth.Entities.User", "User")
                        .WithMany("Cubes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Sessions.Entities.Session", b =>
                {
                    b.HasOne("CubeTimer.WebApi.Contexts.Auth.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Solves.Entities.Solve", b =>
                {
                    b.HasOne("CubeTimer.WebApi.Contexts.Cubes.Entities.Cube", "Cube")
                        .WithMany("Solves")
                        .HasForeignKey("CubeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CubeTimer.WebApi.Contexts.Sessions.Entities.Session", "Session")
                        .WithMany("Solves")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CubeTimer.WebApi.Contexts.Auth.Entities.User", "User")
                        .WithMany("Solves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cube");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Auth.Entities.RefreshToken", b =>
                {
                    b.Navigation("ChildToken");
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Auth.Entities.User", b =>
                {
                    b.Navigation("Cubes");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Sessions");

                    b.Navigation("Solves");
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Cubes.Entities.Cube", b =>
                {
                    b.Navigation("Solves");
                });

            modelBuilder.Entity("CubeTimer.WebApi.Contexts.Sessions.Entities.Session", b =>
                {
                    b.Navigation("Solves");
                });
#pragma warning restore 612, 618
        }
    }
}
